[tools]
"github:lucasew/workspaced" = "0.2.1"
go = "1.25.7"
goreleaser = "2.15.4"
svu = "3.3.0"

[tasks.lint]
run = "workspaced codebase lint"

[tasks.fmt]
run = "workspaced codebase format"

[tasks.format]
run = "workspaced codebase format"

[tasks."build:go"]
run = "go build ./..."

[tasks.build]
depends = ["build:*"]

[tasks."test:go"]
run = "go test -count=1 ./..."
depends = ["build:*"]

[tasks.test]
depends = ["test:*"]

[tasks.ci]
depends = ["lint", "test"]

[tasks."codegen:go"]
run = "go generate ./..."

[tasks.codegen]
depends = ["codegen:*"]

[tasks."install:go"]
run = "go mod download"

[tasks.install]
depends = ["install:*"]

[tasks."docker:build"]
run = "docker build -t ts-proxy:latest ."

[tasks."docker:push"]
run = "docker push ts-proxy:latest"

[tasks.release]
description = "Run a release"
depends = ["ci"]
usage = '''
arg "<version>" help="New version" {
  choices "next" "major" "minor" "patch"
  default "next"
}
'''
run = '''
git tag $(svu ${usage_version})
goreleaser release --clean
'''
